name: Pipeline de testes

on:
  workflow_dispatch:
    push:
      branches:
        - main
      pull_request:
        branches:
          - main

jobs:
  test:
    name: Pipeline de testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o Node
        uses: actions/setup-node@v2

      - name: Instalar dependências
        run: npm install

      - name: Executar os testes
        run: npx cypress run

      - name: Publicar relatório
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'cypress/reports/html'