name: Pipeline de testes

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:
    name: Pipeline de testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar o Node
        uses: actions/setup-node@v2

      - name: Instalar dependências
        run: npm install

      - name: Executar os testes
        run: npx cypress run